<html>
<head>
<style type="text/css">

#container {
	width: 600px;
	border: none;
}

.header {
	background: #2c3e50;
	height: 60px;
	text-align: left;
}

h1 {
	color: #2c3e50;
	font-family: 'Helvetica', 'Arial', sans-serif;
}

#brand {
	color: white;
	font-size: 20pt;
	font-family: 'Helvetica', 'Arial', sans-serif;
	text-decoration: none;
	line-height: 4em;
}

p {
	font-size: 10pt;
	font-family: 'Helvetica', 'Arial', sans-serif;
	color: #777777;
}

hr {
	border: none;
	border-top: 1px solid #777777;
}

</style>
</head>
<body>

<table id="container" cellpadding="5" cellspacing="0">
	<thead>
	<tr class="header">
		<td valign="middle">		
			<img src="<?php echo $message->embed(asset('assets/img/agt_globe.png')); ?>" />
		</td>
		<td valign="middle" width="600">
			<a id="brand" href="#">AGT Hour Tracker</a>
		</td>
	</tr>
	</thead>

	<tbody>
		<tr>
			<td colspan="2">
				<h1>Reminder</h1>
				<p>You are receiving this email because you have not submitted any hours this week to the AGT Hour Tracker application. If you have hours to submit, please <a href="#">do so as soon as possible</a> so that they may be recorded by the accounting department.</p>

			</td>
		</tr>
	</tbody>
</table>

<hr />

<p>
	&copy; <?php echo date('Y'); ?> AGT<br />
	Do not reply to this email, as it was generated by a computer.
</p>


</body>
</html>